config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    resources :doctors do
        member do
          post :create_nurse
          delete :destroy_nurse
        end
      resources :patients do
        member do
          post :create_nurse
          delete :destroy_nurse
          patch :checkup_patient
          patch :xray_patient
          patch :operate_patient
          patch :pay_patient
          patch :wait_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

    

    

end

app/models/patient.rb
class Patient < ActiveRecord::Base

belongs_to :doctor
has_many :patient_medications
has_many :medications, through: :patient_medications
has_many :nurses, as: :nurseable


    BLOOD_TYPE_OPTIONS = [
    ["O-", "O-"],
    ["O+", "O+"],
    ["A-", "A-"],
    ["A+", "A+"],
    ["B-", "B-"],
    ["B+", "B+"],
    ["AB-", "AB-"],
    ["AB+", "AB+"],
  ]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
  validates :description, presence: true
  validates :gender, presence: true
  validates :blood_type, presence: true

include Workflow
  workflow do
    state :waiting_room do
      event :checkup, transitions_to: :checkup_room
      event :xray, transitions_to: :xray_room
      event :operate, transitions_to: :surgery_room
      event :pay, transitions_to: :paybill_room
      event :leave, transitions_to: :left
    end

    state :checkup_room do
      event :xray, transitions_to: :xray_room
      event :operate, transitions_to: :surgery_room
      event :pay, transitions_to: :paybill_room
    end

    state :xray_room do
      event :operate, transitions_to: :surgery_room
      event :pay, transitions_to: :paybill_room
    end

    state :surgery_room do
      event :pay, transitions_to: :paybill_room
    end

    state :paybill_room do
      event :leave, transitions_to: :left
    end

    state :left do
      event :wait, transitions_to: :waiting_room
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [
    :show,
    :edit,
    :update,
    :destroy,
    :wait_patient
  ]

  def index
    @patients = Patient.all
  end
  
  def show
    set_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:id]
    @medications = @patient.medications
    @nurse = Nurse.new
    @nurses = @patient.nurses
  end

  def new
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.new
    @medications = Medication.all

  end

  def create
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.create patient_params
    @medications = Medication.all
    redirect_to doctor_path(@doctor)
  end

  def edit
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.find params[:id]
    @medications = Medication.all

  end

  def update
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.find params[:id]
    @patient.update patient_params
    redirect_to doctor_path(@doctor)
  end

  def destroy
    @patient = Patient.find params[:id]
    @doctor = Doctor.find params[:doctor_id]
    if @patient.delete
      flash[:notice] = 'Patient data was deleted successfully.'
      redirect_to doctor_path(@doctor)
    else
      flash[:notice] = 'Patient data was NOT deleted successfully.'
    end
  end

def create_nurse
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.find params[:id] 
    @nurse = @patient.nurses.create nurse_params
    redirect_to doctor_patient_path(@doctor, @patient)
  end

  def destroy_nurse
    @nurse = Nurse.find params[:nurse_id]
    @nurse.destroy
    redirect_to root_path
  end

def wait_patient
  @doctor = Doctor.find params[:doctor_id]
  @patient = @doctor.patients.find params[:id]
  @patient.wait!
  redirect_to doctor_patient_path
end

def checkup_patient
  @doctor = Doctor.find params[:doctor_id]
  @patient = @doctor.patients.find params[:id]
  @patient.checkup!
  redirect_to doctor_patient_path
end

def xray_patient
  @doctor = Doctor.find params[:doctor_id]
  @patient = @doctor.patients.find params[:id]
  @patient.xray!
  redirect_to doctor_patient_path
end

def operate_patient
  @doctor = Doctor.find params[:doctor_id]
  @patient = @doctor.patients.find params[:id]
  @patient.operate!
  redirect_to doctor_patient_path
end

def pay_patient
  @doctor = Doctor.find params[:doctor_id]
  @patient = @doctor.patients.find params[:id]
  @patient.pay!
  redirect_to doctor_patient_path
end

def leave_patient
  @doctor = Doctor.find params[:doctor_id]
  @patient = @doctor.patients.find params[:id]
  @patient.leave!
  redirect_to doctor_patient_path
end

private
  def patient_params
    params.require(:patient).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :description,
        :gender,
        :blood_type,
        medication_ids: []
      ) 
  end

  def set_doctor
    @doctor = Doctor.find params[:id]
  end

  def set_patient
    @patient = Patient.find params[:id]
  end

  def nurse_params
    params.require(:nurse).permit(
        :name
      )
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
- if @patient.errors.any?
  %p#notice= notice
  - @patient.errors.full_messages.each do |message|
    = message
    %br
%br
  = form_for [@doctor, @patient] do |f|
    %strong= f.label :first_name
    %br
    = f.text_field :first_name
    %br
    %strong= f.label :last_name
    %br
    = f.text_field :last_name
    %br
    %strong= f.label :date_of_birth
    %br
    = f.date_field :date_of_birth
    %br
    %strong= f.label :description
    %br
    = f.text_area :description, size: "30x4"
    %br
    %strong= f.label :gender
    %br
    = f.radio_button(:gender, "male")
    = f.label(:gender, "male")
    = f.radio_button(:gender, "female")
    = f.label(:gender, "female")
    %br
    %br
    %strong= f.label :blood_type
    %br
    = f.select :blood_type, options_for_select(Patient::BLOOD_TYPE_OPTIONS, f.object.blood_type), include_blank: "---Select---"
    %br
    %h3 Prescribed Medications:
    - @medications.each do |medication|
      = check_box_tag 'patient[medication_ids][]', medication.id, @patient.medications.include?(medication)
      = medication.name
      %br
    %br
      / = link_to "Or create a new medication", new_medication_path
      %a.btn.btn-sm.btn-success{:href => new_medication_path, :role => "button"} Or create a new medication
      %br
      %br
        = f.submit
  %a.btn.btn-sm.btn-primary{:href => doctor_path(@doctor), :role => "button"} Cancel
  %a.btn.btn-sm.btn-primary{:href => root_path, :role => "button"} Return to Home »

  %br
  %br

app/views/patients/edit.html.haml
%h1{:colspan => "2", :style => "text-align:center;"}
  %u Edit Patient Data

= render 'form'

app/views/patients/index.html.haml
%p#notice= notice
%h1 Patients
%br
= link_to "Create New Patient Data", new_patient_path
%br
  %ul
    - @patients.each do |patient|
      %li
        %strong Patient Name:
        = link_to patient.last_name + ", " + patient.first_name, patient_path(patient)
        %br
        %strong DOB:
        = patient.date_of_birth
        %br
        %strong Description:
        = patient.description
        %br
        %strong Gender:
        = patient.gender
        %br
        %strong Blood Type:
        = patient.blood_type
        %br
        %br
= link_to "Edit Patient", edit_patient_path(patient)
|
= link_to "Delete Patient", patient_path(patient), method: :delete
%br
= link_to "Return to Home", root_path

app/views/patients/new.html.haml
%h1{:colspan => "2", :style => "text-align:center;"}
  %u Enter New Patient Data

= render 'form'

app/views/patients/show.html.haml
%h1 
  %u Information for:
  %h2= @patient.last_name + ", " + @patient.first_name
  %strong DOB:
  = @patient.date_of_birth
  %br
  %strong Description:
  = @patient.description
  %br
  %strong Gender:
  = @patient.gender
  %br
  %strong Blood Type:
  = @patient.blood_type
  %br
  %br
  %h5
    %strong Patient Location:
    = @patient.workflow_state
    - if @patient.waiting_room?
      %i.fa.fa-user-md.fa-lg
      =link_to "Checkup", checkup_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-times.fa-lg
      = link_to "Recieve X-Ray", xray_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-bed.fa-lg
      = link_to "Start Surgery", operate_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-usd.fa-lg
      = link_to "Bill Patient", pay_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-sign-out.fa-lg
      = link_to "Discharge Patient", leave_patient_doctor_patient_path(@doctor, @patient), method: :patch
    - if @patient.checkup_room?
      %i.fa.fa-times.fa-lg
      = link_to "Recieve X-Ray", xray_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-bed.fa-lg
      = link_to "Start Surgery", operate_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-usd.fa-lg
      = link_to "Bill Patient", pay_patient_doctor_patient_path(@doctor, @patient), method: :patch
    - if @patient.xray_room?
      %i.fa.fa-bed.fa-lg
      = link_to "Start Surgery", operate_patient_doctor_patient_path(@doctor, @patient), method: :patch
      %i.fa.fa-usd.fa-lg
      = link_to "Bill Patient", pay_patient_doctor_patient_path(@doctor, @patient), method: :patch
    - if @patient.surgery_room?
      %i.fa.fa-usd.fa-lg
      = link_to "Bill Patient", pay_patient_doctor_patient_path(@doctor, @patient), method: :patch
    - if @patient.paybill_room?
      %i.fa.fa-sign-out.fa-lg
      = link_to "Discharge Patient", leave_patient_doctor_patient_path(@doctor, @patient), method: :patch
    - if @patient.left?
      %i.fa.fa-refresh.fa-spin
      = link_to "Begin Intake", wait_patient_doctor_patient_path(@doctor, @patient), method: :patch
%br
%br
= link_to "Edit Patient", edit_doctor_patient_path(@doctor, @patient)
|
= link_to "Delete Patient", doctor_patient_path(@doctor, @patient), method: :delete
%br
= link_to "Return to Doctor", doctor_path(@doctor)
|
= link_to "Return to Main", root_path
%br
%h3
  %u Patient's Medications:
= link_to "Add Medication", new_medication_path
%br
%br
  %ul
    - @patient.medications.each do |medication|
      %li
        %strong Medication Name:
        = medication.name
        %br
        %strong Side Effects:
        = medication.side_effects
        %br
        = link_to "Edit Medication", edit_medication_path(medication), class: "btn-sm btn-success"
        |
        = link_to "Delete Medication", medication_path(medication), method: :delete, class: "btn-sm btn-danger", data: { confirm: 'Are you sure?' }
%br
%h3
  %u Patient's Preferred Nurses:
%br
- @nurses.each do |nurse|
  %li
    = nurse.name
    = link_to "Remove", destroy_nurse_doctor_patient_path(@doctor, @patient, nurse_id: nurse.id), method: :delete, class: "btn-sm btn-danger", data: { confirm: 'Are you sure?' }
    %br
    %br
= form_for @nurse, url: create_nurse_doctor_patient_path(@doctor, @patient) do |f|
  = f.text_field :name, placeholder: "Add Nurse"
  = f.submit
  %br