config/routes.rb
Rails.application.routes.draw do
    root 'home#index'

    resources :doctors do
        member do
          post :create_nurse
          delete :destroy_nurse
        end
      resources :patients do
        member do
          post :create_nurse
          delete :destroy_nurse
          patch :checkup_patient
          patch :xray_patient
          patch :operate_patient
          patch :pay_patient
          patch :wait_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

    

    

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

  has_many :patients, dependent: :destroy
  has_many :nurses, as: :nurseable

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = Doctor.all
      # if !params[:search].blank?
      #      @posts = Post.where("name LIKE ?", "%#{params[:search]}%")
      #    else
      #      @posts = @user.posts
      #    end
  end

  def show
    set_doctor
    @patients = @doctor.patients
    @nurse = Nurse.new
    @nurses = @doctor.nurses
    # @nurses = @patient.nurses
  end

  def new
    @doctor = Doctor.new
  end

  def create_nurse
    @doctor = Doctor.find params[:id]
    @nurse = @doctor.nurses.create nurse_params
    redirect_to doctor_path(@doctor)
  end

  def destroy_nurse
    @nurse = Nurse.find params[:id]
    @nurse.destroy
    redirect_to@nurse.nurseable
  end

  def create
    @doctor = Doctor.create doctor_params
    if @doctor.save
      flash[:notice] = 'Physician data was saved successfully.'
      redirect_to doctors_path
    else
      flash[:error] = 'Physician data was NOT saved successfully.'
      render :new
    end
  end

  def edit
    @doctor = Doctor.find params[:id]
  end

  def update
    @doctor = Doctor.find params[:id]
    @doctor.update_attributes doctor_params
    redirect_to doctors_path
  end

  def destroy
    @doctor = Doctor.find params[:id]
    @doctor.delete
    redirect_to doctors_path
  end

  
  private

    def set_doctor
    @doctor = Doctor.find params[:id]
  end

    def doctor_params
      params.require(:doctor).permit(
        :first_name,
        :last_name,
        :biography,
        :gender_name,
        :specialty,
      ) 
  end

  def nurse_params
    params.require(:nurse).permit(
        :name
      )
  end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
= form_for @doctor do |f|
  %br
    = f.label :first_name    
    = f.text_field :first_name
    = f.label :last_name
    = f.text_field :last_name
    = f.label :biography
    = f.text_area :biography, size: "30x4"
    = f.radio_button :gender_name, "male"
    = f.label(:gender_name, "male")
    = f.radio_button(:gender_name, "female")
    = f.label(:gender_name, "female")
    %br
    %br
    = f.label :specialty
    = f.text_field :specialty
    %br
    %br
    = f.submit
    %br
    %a.btn.btn-primary.btn-lg.btn-block{:href => doctors_path, :role => "button"} Return To Physicians Page »
    %br
    
/ %label.radio-inline
/   %input#inlineRadio1{:name => "inlineRadioOptions", :type => "radio", :value => "option1"}
/     1
/ %label.radio-inline
/   %input#inlineRadio2{:name => "inlineRadioOptions", :type => "radio", :value => "option2"}
/     2

app/views/doctors/edit.html.haml
%h1{:colspan => "2", :style => "text-align:center;"}
  %u Edit Physician Information
= render 'form'

app/views/doctors/index.html.haml
%h1{:colspan => "2", :style => "text-align:center;"}
  %u Our Physicians
%p#notice= notice
%br
%br
/ =form_tag user_posts_path, method: :get, class: "form-search", role: "search" do
/  .input-group
/    =text_field_tag 'search', params[:search], class: "form-control", id: "srch-term", placeholder: "Search"
/    .input-group-btn
/      %button.btn.btn-default{:style => "width:40px;"}
/        %span.glyphicon.glyphicon-search
/  %br
/ = link_to 'Home Page', root_path
.col-md-5
  %a.btn.btn-primary.btn-lg.btn-block{:href => root_path, :role => "button"} Home Page »
  %br
  %ul
  - @doctors.each do |doctor|
    %strong Name:
    = doctor.first_name
    = doctor.last_name
    %br
      %strong Gender:
      = doctor.gender_name
      %br
        %strong Specialty:
        = doctor.specialty
      / = link_to 'More Information', doctor_path(doctor)
      %a.btn.btn-sm.btn-info{:href => doctor_path(doctor), :role => "button"} More Information
      / = link_to 'Edit', edit_doctor_path(doctor)
      %a.btn.btn-sm.btn-warning{:href => edit_doctor_path(doctor), :role => "button"} Edit Information
      %br
      %br
  / = link_to 'Enter New Physician', new_doctor_path
  %a.btn.btn-primary.btn-lg.btn-block{:href => new_doctor_path, :role => "button"} Enter New Physician »

app/views/doctors/new.html.haml
%h1{:colspan => "2", :style => "text-align:center;"}
  Enter New Physician Information
= render 'form'

app/views/doctors/show.html.haml
%h1{:colspan => "2", :style => "text-align:center;"}
  %u Physician Information
%br
%strong Name:
= @doctor.first_name
= @doctor.last_name
%br
%strong Gender:
= @doctor.gender_name
%br
%strong Specialty:
= @doctor.specialty
%br
%br
%strong Biography:
= @doctor.biography
%br
%br
/ %a.btn.btn-sm.btn-warning{:href => edit_doctor_path(@doctor), :role => "button"} Edit This Doctor
= link_to "Edit This Doctor", edit_doctor_path(@doctor), class: "btn btn-warning"
/ =link_to "Remove This Doctor", doctor_path(@doctor), method: :delete, data: { confirm: 'Are you sure you want to delete?'}
/ %a.btn.btn-sm.btn-danger{:href => doctor_path(@doctor), method: :delete, :role => "button"} Delete This Doctor
= link_to "Remove This Doctor", doctor_path(@doctor), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' }
/ %a.btn.btn-sm.btn-primary{:href => doctors_path, :role => "button"} List of Doctors »
= link_to "List of Doctors »", doctors_path, class: "btn btn-primary"
/ %a.btn.btn-sm.btn-primary{:href => root_path, :role => "button"} Return to Home »
= link_to "Return to Home »", root_path, class: "btn btn-primary"

%br
%br
%h3
  %u Physician's Current Patients:

%br
- @patients.each do |patient|
  %li
    %strong Name:
    = link_to patient.last_name + ", " + patient.first_name, doctor_patient_path(@doctor, patient)
    %br
    %strong Date of Birth:
    = patient.date_of_birth
    %br
    %strong Description:
    = patient.description
    %br
    %strong Gender:
    = patient.gender
    %br
    %strong Blood Type:
    = patient.blood_type
    %br
    / = link_to "Edit Patient Information", edit_doctor_patient_path(@doctor, patient)
    / %a.btn.btn-sm.btn-warning{:href => edit_doctor_patient_path(@doctor, patient), :role => "button"} Edit Patient Information
    = link_to "Edit Patient Information", edit_doctor_patient_path(@doctor, patient), class: "btn-sm btn-warning"
    / %a.btn.btn-sm.btn-danger{:href => doctor_patient_path(@doctor, patient), method: :delete, :role => "button"} Delete Patient Information
    = link_to "Remove Patient Information", doctor_patient_path(@doctor, patient), method: :delete, class: "btn-sm btn-danger", data: { confirm: 'Are you sure?' }
    %br
    %br
    %br
/ %a.btn.btn-sm.btn-success{:href => new_doctor_patient_path(@doctor), :role => "button"} Add New Patient
= link_to "Add New Patient »", new_doctor_patient_path(@doctor), class: "btn-sm btn-success"

%br
%br
%h3
  %u Physicians's List of Nurses:
%br
- @nurses.each do |nurse|
  %li
    = nurse.name
    = link_to "Remove", destroy_nurse_doctor_path(nurse), method: :delete, class: "btn-sm btn-danger", data: { confirm: 'Are you sure?' }
    %br
    %br
= form_for @nurse, url: create_nurse_doctor_path(@doctor) do |f|
  = f.text_field :name, placeholder: "Add Nurse"
  = f.submit